# Model arguments
model_name_or_path: Unbabel/7B_all_mc4_wiki_20b_20b_ckpt
model_revision: main
tokenizer_name_or_path: data/towerllm-instruct-tokenizer
tokenizer_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  Unbabel/TowerLLM-instruction-tuning-HW_0611: 1.0
dataset_splits:
  - train
  - validation
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
hub_model_id: Unbabel/towerllm-instruct-HW_0611
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 10  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: data/towerllm-instruct-HW_0611
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "no"
save_total_limit: null
seed: 42
tf32: true